'use client'
import { useEffect, useState } from 'react'
import { createClient } from '@/lib/supabase/client'
export default function AdminUpdates(){
 const [items,setItems]=useState<any[]>([]); const [body,setBody]=useState(''); const [published,setPublished]=useState(true); const [editing,setEditing]=useState<string|null>(null); const [msg,setMsg]=useState('')
 async function load(){const supabase=createClient();const {data}=await supabase.from('updates').select('*').order('created_at',{ascending:false});setItems(data||[])} useEffect(()=>{load()},[])
 async function save(e:any){e.preventDefault();const supabase=createClient();const now=new Date().toISOString();const payload={body,published,published_at:published?now:null,updated_at:now};const r=editing?await supabase.from('updates').update(payload).eq('id',editing):await supabase.from('updates').insert(payload);setMsg(r.error?r.error.message:'Saved.');if(!r.error){setBody('');setEditing(null);load()}}
 async function remove(id:string){if(!confirm('Delete this update?'))return;const supabase=createClient();const r=await supabase.from('updates').delete().eq('id',id);setMsg(r.error?r.error.message:'Deleted.');if(!r.error)load()}
 function edit(u:any){setEditing(u.id);setBody(u.body);setPublished(u.published)}
 return <main className="shell page adminEditor"><header className="adminHeader"><a className="brand" href="/admin">LAUNCH9<span>LABS</span></a><a href="/admin">← Dashboard</a></header><div className="pageHeader"><span className="sectionNumber">CMS // UPDATES</span><h1>Publish<br/><em>updates.</em></h1></div><section className="editorLayout"><form className="editorForm" onSubmit={save}><h2>{editing?'Edit update':'New update'}</h2><label>Post<textarea required value={body} onChange={e=>setBody(e.target.value)} placeholder="What are you building?"/></label><label className="check"><input type="checkbox" checked={published} onChange={e=>setPublished(e.target.checked)}/> Published</label><div className="formActions"><button className="button primary">{editing?'Save changes':'Publish update'}</button>{editing&&<button type="button" onClick={()=>{setEditing(null);setBody('');setPublished(true)}}>Cancel</button>}</div>{msg&&<p>{msg}</p>}</form><div className="editorList"><h2>Updates</h2>{items.map(u=><article className="editorItem" key={u.id}><div><small>{u.published?'PUBLISHED':'DRAFT'}</small><p>{u.body}</p></div><div><button onClick={()=>edit(u)}>Edit</button><button onClick={()=>remove(u.id)}>Delete</button></div></article>)}{!items.length&&<p>No updates yet.</p>}</div></section></main>
}
