'use client'

import { FormEvent, useEffect, useState } from 'react'
import { createClient } from '@/lib/supabase/client'

export default function AdminSettings(){
 const supabase=createClient(); const [form,setForm]=useState({site_name:'Launch9 Labs',tagline:'',description:'',contact_email:'',socials:'{}'}); const [msg,setMsg]=useState(''); const [busy,setBusy]=useState(false)
 useEffect(()=>{supabase.from('site_settings').select('*').limit(1).maybeSingle().then(({data})=>{if(data)setForm({site_name:data.site_name||'',tagline:data.tagline||'',description:data.description||'',contact_email:data.contact_email||'',socials:JSON.stringify(data.socials||{},null,2)})})},[])
 function set(k:string,v:string){setForm(f=>({...f,[k]:v}))}
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setMsg('');let socials={};try{socials=JSON.parse(form.socials||'{}')}catch{setMsg('Social links must be valid JSON.');setBusy(false);return}const {data}=await supabase.from('site_settings').select('id').limit(1).maybeSingle();const payload={site_name:form.site_name,tagline:form.tagline,description:form.description,contact_email:form.contact_email,socials,updated_at:new Date().toISOString()};const r=data?await supabase.from('site_settings').update(payload).eq('id',data.id):await supabase.from('site_settings').insert(payload);setMsg(r.error?r.error.message:'Saved.');setBusy(false)}
 return <main className="shell page adminPage"><header className="adminHeader"><div><a className="brand" href="/admin">LAUNCH9<span>LABS</span></a><p>Site settings</p></div><a href="/">View site ↗</a></header><div className="pageHeader"><span className="sectionNumber">SETTINGS // SITE</span><h1>Control the<br/><em>studio.</em></h1></div><form className="adminForm" onSubmit={save}><label>Site name<input value={form.site_name} onChange={e=>set('site_name',e.target.value)}/></label><label>Tagline<input value={form.tagline} onChange={e=>set('tagline',e.target.value)}/></label><label>Description<textarea value={form.description} onChange={e=>set('description',e.target.value)}/></label><label>Contact email<input type="email" value={form.contact_email} onChange={e=>set('contact_email',e.target.value)}/></label><label>Social links <small>JSON, e.g. {`{"github":"https://github.com/...","x":"https://x.com/..."}`}</small><textarea value={form.socials} onChange={e=>set('socials',e.target.value)}/></label><div className="formActions"><button className="button primary" disabled={busy}>{busy?'Saving…':'Save settings'}</button>{msg&&<span>{msg}</span>}</div></form><a className="back" href="/admin">← Back to workspace</a></main>
}
