'use client'

import { FormEvent, useEffect, useState } from 'react'
import { createClient } from '@/lib/supabase/client'

type Project = { id:string; name:string; slug:string; description:string|null; status:string; url:string|null; tags:string[]; featured:boolean }
const empty={name:'',slug:'',description:'',status:'in_development',url:'',tags:'',featured:false}

export default function AdminProjects(){
 const [items,setItems]=useState<Project[]>([]); const [form,setForm]=useState(empty); const [editing,setEditing]=useState<string|null>(null); const [busy,setBusy]=useState(false); const [msg,setMsg]=useState('')
 async function load(){const supabase=createClient();const {data}=await supabase.from('projects').select('*').order('sort_order');setItems(data||[])}
 useEffect(()=>{load()},[])
 function edit(p:Project){setEditing(p.id);setForm({name:p.name,slug:p.slug,description:p.description||'',status:p.status,url:p.url||'',tags:(p.tags||[]).join(', '),featured:p.featured})}
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setMsg('');const supabase=createClient();const payload={name:form.name,slug:form.slug||form.name.toLowerCase().trim().replace(/[^a-z0-9]+/g,'-'),description:form.description,status:form.status,url:form.url||null,tags:form.tags.split(',').map(x=>x.trim()).filter(Boolean),featured:form.featured,updated_at:new Date().toISOString()};const result=editing?await supabase.from('projects').update(payload).eq('id',editing):await supabase.from('projects').insert(payload);if(result.error)setMsg(result.error.message);else{setForm(empty);setEditing(null);setMsg('Saved.');await load()}setBusy(false)}
 async function remove(id:string){if(!confirm('Delete this project?'))return;const supabase=createClient();await supabase.from('projects').delete().eq('id',id);await load()}
 return <main className="shell page adminEditor"><header className="adminHeader"><a className="brand" href="/admin">LAUNCH9<span>LABS</span></a><a href="/admin">← Dashboard</a></header><div className="pageHeader"><span className="sectionNumber">CMS // PROJECTS</span><h1>Manage<br/><em>projects.</em></h1></div><section className="editorLayout"><form className="editorForm" onSubmit={save}><h2>{editing?'Edit project':'New project'}</h2><label>Name<input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/></label><label>Slug<input value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})} placeholder="auto-generated if blank"/></label><label>Description<textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><label>Status<select value={form.status} onChange={e=>setForm({...form,status:e.target.value})}><option value="idea">Idea</option><option value="in_development">In development</option><option value="beta">Beta</option><option value="live">Live</option><option value="paused">Paused</option><option value="archived">Archived</option></select></label><label>URL<input value={form.url} onChange={e=>setForm({...form,url:e.target.value)}/></label><label>Tags<input value={form.tags} onChange={e=>setForm({...form,tags:e.target.value})} placeholder="Design, Productivity"/></label><label className="check"><input type="checkbox" checked={form.featured} onChange={e=>setForm({...form,featured:e.target.checked})}/> Featured</label><div><button className="button primary" disabled={busy}>{busy?'Saving…':editing?'Save changes':'Add project'}</button>{editing&&<button type="button" className="button" onClick={()=>{setEditing(null);setForm(empty)}}>Cancel</button>}</div>{msg&&<p>{msg}</p>}</form><div className="editorList"><h2>Current projects</h2>{items.map(p=><article className="editorItem" key={p.id}><div><small>{p.status}</small><h3>{p.name}</h3><p>{p.description}</p></div><div><button onClick={()=>edit(p)}>Edit</button><button onClick={()=>remove(p.id)}>Delete</button></div></article>)}{!items.length&&<p>No projects yet.</p>}</div></section></main>
}
