'use client'

import { FormEvent, useEffect, useState } from 'react'
import { createClient } from '@/lib/supabase/client'

type Home = { id:string; headline:string; subtitle:string|null; primary_cta_label:string|null; primary_cta_url:string|null; secondary_cta_label:string|null; secondary_cta_url:string|null; hero_image_url:string|null }
const blank={headline:'',subtitle:'',primary_cta_label:'',primary_cta_url:'',secondary_cta_label:'',secondary_cta_url:'',hero_image_url:''}

export default function AdminHomepage(){
 const [form,setForm]=useState(blank); const [id,setId]=useState<string|null>(null); const [msg,setMsg]=useState(''); const [busy,setBusy]=useState(false)
 useEffect(()=>{(async()=>{const s=createClient();const {data}=await s.from('homepage_content').select('*').limit(1).maybeSingle();if(data){setId(data.id);setForm({headline:data.headline||'',subtitle:data.subtitle||'',primary_cta_label:data.primary_cta_label||'',primary_cta_url:data.primary_cta_url||'',secondary_cta_label:data.secondary_cta_label||'',secondary_cta_url:data.secondary_cta_url||'',hero_image_url:data.hero_image_url||''})}})()},[])
 async function save(e:FormEvent){e.preventDefault();setBusy(true);setMsg('');const s=createClient();const payload={...form,updated_at:new Date().toISOString()};const r=id?await s.from('homepage_content').update(payload).eq('id',id):await s.from('homepage_content').insert(payload).select().single();if(r.error)setMsg(r.error.message);else{if(r.data?.id)setId(r.data.id);setMsg('Homepage saved.')}setBusy(false)}
 return <main className="shell page adminEditor"><header className="adminHeader"><a className="brand" href="/admin">LAUNCH9<span>LABS</span></a><a href="/admin">← Dashboard</a></header><div className="pageHeader"><span className="sectionNumber">CMS // HOMEPAGE</span><h1>Edit<br/><em>homepage.</em></h1></div><section className="editorLayout"><form className="editorForm" onSubmit={save}><h2>Hero content</h2><label>Headline<textarea required value={form.headline} onChange={e=>setForm({...form,headline:e.target.value})}/></label><label>Subtitle<textarea value={form.subtitle} onChange={e=>setForm({...form,subtitle:e.target.value})}/></label><h2>Primary button</h2><label>Label<input value={form.primary_cta_label} onChange={e=>setForm({...form,primary_cta_label:e.target.value})}/></label><label>URL<input value={form.primary_cta_url} onChange={e=>setForm({...form,primary_cta_url:e.target.value})}/></label><h2>Secondary button</h2><label>Label<input value={form.secondary_cta_label} onChange={e=>setForm({...form,secondary_cta_label:e.target.value})}/></label><label>URL<input value={form.secondary_cta_url} onChange={e=>setForm({...form,secondary_cta_url:e.target.value})}/></label><h2>Hero image</h2><label>Image URL<input value={form.hero_image_url} onChange={e=>setForm({...form,hero_image_url:e.target.value})} placeholder="Optional"/></label><button className="button primary" disabled={busy}>{busy?'Saving…':'Save homepage'}</button>{msg&&<p>{msg}</p>}</form><aside className="editorList"><h2>What this controls</h2><p>These fields change the live homepage without editing code.</p><p>Projects and updates are managed separately from the dashboard.</p></aside></section></main>
}
